git clone git@github.com:alex-chin/caliber.git
git clone git@github.com:alex-chin/data_mining_20_04_2021.git
git clone git@github.com:alex-chin/gb_business.git
git clone git@github.com:alex-chin/gb_business_class.git
git clone git@github.com:alex-chin/gb_data_analysis.git
git clone git@github.com:alex-chin/gb_data_collection_py.git
git clone git@github.com:alex-chin/GB_HI_MATH.git
git clone git@github.com:alex-chin/GB_LIBS_DS.git
git clone git@github.com:alex-chin/GB_LIBS_DS2.git
git clone git@github.com:alex-chin/GB_LINEAR_ALGEBRA.git
git clone git@github.com:alex-chin/GB_linux.git
git clone git@github.com:alex-chin/gb_megafone1.git
git clone git@github.com:alex-chin/GB_mysql.git
git clone git@github.com:alex-chin/gb_prob_stat.git
git clone git@github.com:alex-chin/GB_Python_algorithms.git
git clone git@github.com:alex-chin/git-project.git
git clone git@github.com:alex-chin/mapdroid.git
git clone git@github.com:alex-chin/projects.git
git clone git@github.com:alex-chin/project_gb2.git
git clone git@github.com:alex-chin/python_13_10_2020.git
git clone git@github.com:alex-chin/python_basic_13_10_2020.git
git clone git@github.com:alex-chin/RecSys.git
git clone git@github.com:alex-chin/st.base_ml.git